name: run-tests

on:
  pull_request:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: install requirements
        run: pip install -r requirements.txt
        shell: bash

      - name: run test
        run: python generate_slicer_json.py test_data/terminology_test.csv
        shell: bash
