name: Validate JSON
# adapted from https://github.com/walbo/validate-json.git

on:
  pull_request:
    paths:
      - '**.py'
  push:
    #branches: 
   #   - main
   #   - 'feature/**'
   # paths:
   #   - '**.py'
      
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: install requirements
        run: pip install -r requirements.txt
        shell: bash

      - name: set JSON
        id: step_json
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "JSON_OUTPUT<<$EOF" >> $GITHUB_OUTPUT
          python generate_slicer_json.py test_data/terminology_test.csv >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: ${{ steps.step_json.outputs.JSON_OUTPUT }} #folder/**/*.json

          # optional, defaults to `$schema` in your JSON file
          schema: schemas/schema.json

          # optional, default: draft-04
          schema-version: draft-04

          # optional, default: false
          print-valid-files: false

          # optional, default: false
          fail-on-missing-schema: false

          # optional, default: true
          strict: true

          # optional, default: false
          allow-matching-properties: false

          # optional, default: true
          allow-union-types: true
